name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        NODE_ENV: production
        # Remove this line if you would like to skip using google analytics
        REACT_APP_GA_TRACKING_ID: UA-68649021-1
        # This is set automatically by github
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://github.com/ddabed/ddabed.github.io.git
          npm run deploy
